# NumPy (Numerical Python) Library Methods 

In [ ]:
#  How to import thr numpy library in Jupyter notebook

In [1]:
import numpy as np

Creating  One dimenssional array 

In [2]:
a =  np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
print(a.shape)

(3,)


In [8]:
print(a.size)

3


In [9]:
b = np.array([[1,2,3],[1,2,3]])

In [10]:
print(b)

[[1 2 3]
 [1 2 3]]


In [11]:
print(b.shape)

(2, 3)


In [12]:
print(b.size)

6


In [18]:
c = np.zeros(3,dtype = "int16")

In [19]:
c

array([0, 0, 0], dtype=int16)

In [ ]:
# to create arrays of ones

In [21]:
d = np.ones(3,dtype = 'int16')

In [22]:
d

array([1, 1, 1], dtype=int16)

In [ ]:
# create array with range

In [26]:
e = np.arange(0,20)

In [27]:
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
# to reshape the array

In [29]:
print(e.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
# create array with linespace

In [30]:
f = np.linspace(0,20,5)

In [31]:
f

array([ 0.,  5., 10., 15., 20.])

In [37]:
g = np.linspace(0,10)


In [40]:
print(g.shape)

(50,)


In [41]:
# creating multidimessional array

In [46]:
a1 = np.eye(3)

In [47]:
a1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
a1[0][0]

1.0

In [49]:
a2 = np.eye(3,5)

In [50]:
a2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
# how to get tthe diagonal elements 

In [56]:
a4 = np.arange(0,9).reshape(3,3)

In [57]:
a4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
print(np.diag(a4))

[0 4 8]


In [64]:
print(np.diag(a4, k =1))

[2]


Create a diagonal elements as 1,2,3,4 but 1 at coloumn 2

In [65]:
a3 = np.diag([1,2,3,4], k =2)

In [66]:
a3

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
# creating a numpy array using a random function

In [68]:
from numpy.random import default_rng as dr

In [73]:
dr(10).random((2,3))

array([[0.95600171, 0.20768181, 0.82844489],
       [0.14928212, 0.51280462, 0.1359196 ]])

How to acess the items in numpy

In [74]:
a3

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [76]:
a3[0][1] = 5

In [77]:
a3

array([[0, 5, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [80]:
a3[4][1] = 1

In [81]:
a3

array([[0, 5, 1, 0, 0, 0],
       [0, 1, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

Remarks:
    
    1) Numpy(NUmeric Python) is a n dimentonal array 
    2) It is open source python library 
    3) Some iportant methods of the numpy is as :
        1) np.array()
        2) np.ones()
        3) np.eye()
        4) np.zeros()
        5) np.reshape()
        6) np.diag()
        7) np.sort()
        8) np.[][] to access the item in the array
        9) 